
export const SMOKE_CONFIG = {
  PARTICLE_COUNT: 4000,
  PARTICLE_BASE_SIZE: 1.5,
  PARTICLE_SIZE_VARIATION: 1,
  MOUSE_RADIUS: 65,
  REPULSION_STRENGTH: 4,
  RETURN_SPEED: 0.008,
  FRICTION: 0.97,
  INHERENT_DRIFT_SPEED: 0.1,
  MAX_VELOCITY: 0.8,
  CLOUD_CENTER_X_FACTOR: 0.5,
  CLOUD_CENTER_Y_FACTOR: 0.6,
  CLOUD_WIDTH_FACTOR: 0.8,
  CLOUD_HEIGHT_FACTOR: 0.35,
  PARTICLE_COLOR: [200, 200, 215] as const,
  PARTICLE_BASE_OPACITY: 0.08,
  PARTICLE_OPACITY_VARIATION: 0.05,
  CANVAS_CLEAR_OPACITY: 0.85,
  BACKGROUND_COLOR_RGBA: 'rgba(15, 14, 23)'
} as const;
