
export const PARTICLE_CONFIG = {
  PARTICLE_COUNT: 1200,
  PARTICLE_BASE_SIZE: 6,
  PARTICLE_SIZE_VARIATION: 4,
  MOUSE_RADIUS: 70,
  REPULSION_STRENGTH: 3,
  RETURN_SPEED: 0.01,
  FRICTION: 0.96,
  INHERENT_DRIFT: 0.15,
  MAX_VELOCITY: 1.5
} as const;

export const CLOUD_CONFIG = {
  CENTER_X_FACTOR: 0.5,
  CENTER_Y_FACTOR: 0.6,
  WIDTH_FACTOR: 0.7,
  HEIGHT_FACTOR: 0.4
} as const;

export const CANVAS_CONFIG = {
  CLEAR_OPACITY: 0.4,
  BACKGROUND_COLOR: 'rgba(15, 14, 23)'
} as const;
